#!/bin/bash
# the proposed learner, final protocol, two sets of five training seeds: sppoX_fast5_s* (2 rollout processes; run on the rented 3090) and sppoX_fast_s* (4 rollout processes; run on server 182) - same seeds and settings, different random streams
# GENERATED by tools/build.py from the as-run chain scripts (as_run/) - edit the generator, not this file.
# usage: bash exp/10_train_proposed.sh        (settings: env.sh; output directory: $OUT; SMOKE=1 for a quick execution test)
source "$(dirname "$0")/../lib.sh"

COMMON="BUB_ALTS=39,69.5,100 BUB_BETA=300 BUB_IOT_DB=20.1 BUB_NTOK_CV=0 BUB_PORTS=4 BUB_QBAR=0.44 BUB_QMARGIN=0.008 BUB_V=0.3 BUB_ZMODE=uav EVAL_LAMS=55,60,65 MKL_NUM_THREADS=2 OMP_NUM_THREADS=2 PPO_LAMS=55,60,65 PPO_LAMS_TEST=60,65 SPPO_LRS=1.5e-1 SPPO_MODE=struct"

runbg sppoX_fast5_s0.json $COMMON PPO_SEED=30 -- sppo_hold.py sim_inputs.json sppoX_fast5_s0.json 0.44 4 60 2 500
runbg sppoX_fast5_s1.json $COMMON PPO_SEED=31 -- sppo_hold.py sim_inputs.json sppoX_fast5_s1.json 0.44 4 60 2 500
runbg sppoX_fast5_s2.json $COMMON PPO_SEED=32 -- sppo_hold.py sim_inputs.json sppoX_fast5_s2.json 0.44 4 60 2 500
runbg sppoX_fast5_s3.json $COMMON PPO_SEED=33 -- sppo_hold.py sim_inputs.json sppoX_fast5_s3.json 0.44 4 60 2 500
runbg sppoX_fast5_s4.json $COMMON PPO_SEED=34 -- sppo_hold.py sim_inputs.json sppoX_fast5_s4.json 0.44 4 60 2 500
runbg sppoX_fast_s0.json $COMMON PPO_SEED=30 -- sppo_hold.py sim_inputs.json sppoX_fast_s0.json 0.44 4 60 4 500
runbg sppoX_fast_s1.json $COMMON PPO_SEED=31 -- sppo_hold.py sim_inputs.json sppoX_fast_s1.json 0.44 4 60 4 500
runbg sppoX_fast_s2.json $COMMON PPO_SEED=32 -- sppo_hold.py sim_inputs.json sppoX_fast_s2.json 0.44 4 60 4 500
runbg sppoX_fast_s3.json $COMMON PPO_SEED=33 -- sppo_hold.py sim_inputs.json sppoX_fast_s3.json 0.44 4 60 4 500
runbg sppoX_fast_s4.json $COMMON PPO_SEED=34 -- sppo_hold.py sim_inputs.json sppoX_fast_s4.json 0.44 4 60 4 500
waitall
report
