#!/bin/bash
# the comparison learners (H-PPO = B, penalty PPO = C, D3QN, TD3): five training seeds at M = 4, seed 0 trained for M = 3 and 5
# GENERATED by tools/build.py from the as-run chain scripts (as_run/) - edit the generator, not this file.
# usage: bash exp/11_train_baselines.sh        (settings: env.sh; output directory: $OUT; SMOKE=1 for a quick execution test)
source "$(dirname "$0")/../lib.sh"

COMMON="BUB_ALTS=39,69.5,100 BUB_BETA=500 BUB_IOT_DB=20.1 BUB_NTOK_CV=0 BUB_PORTS=4 BUB_QBAR=0.44 BUB_QMARGIN=0.008 BUB_V=0.03 BUB_ZMODE=uav EVAL_LAMS=55,60,65 PPO_LAMS=55,60,65 PPO_LAMS_TEST=60,65"

runbg mrl5k_B_M4_s0.json $COMMON BUB_PRIOR_P=1 MKL_NUM_THREADS=2 OMP_NUM_THREADS=2 PPO_BASE=urg PPO_PRIOR=0 PPO_REWARD=queue PPO_SEED=0 -- hppo_hold.py sim_inputs.json mrl5k_B_M4_s0.json 0.44 4 60 2 625
runbg mrl5k_B_M4_s1.json $COMMON BUB_PRIOR_P=1 MKL_NUM_THREADS=2 OMP_NUM_THREADS=2 PPO_BASE=urg PPO_PRIOR=0 PPO_REWARD=queue PPO_SEED=1 -- hppo_hold.py sim_inputs.json mrl5k_B_M4_s1.json 0.44 4 60 2 625
runbg mrl5k_B_M4_s2.json $COMMON BUB_PRIOR_P=1 MKL_NUM_THREADS=2 OMP_NUM_THREADS=2 PPO_BASE=urg PPO_PRIOR=0 PPO_REWARD=queue PPO_SEED=2 -- hppo_hold.py sim_inputs.json mrl5k_B_M4_s2.json 0.44 4 60 2 625
runbg mrl5k_B_M4_s3.json $COMMON BUB_PRIOR_P=1 MKL_NUM_THREADS=2 OMP_NUM_THREADS=2 PPO_BASE=urg PPO_PRIOR=0 PPO_REWARD=queue PPO_SEED=3 -- hppo_hold.py sim_inputs.json mrl5k_B_M4_s3.json 0.44 4 60 2 625
runbg mrl5k_B_M4_s4.json $COMMON BUB_PRIOR_P=1 MKL_NUM_THREADS=2 OMP_NUM_THREADS=2 PPO_BASE=urg PPO_PRIOR=0 PPO_REWARD=queue PPO_SEED=4 -- hppo_hold.py sim_inputs.json mrl5k_B_M4_s4.json 0.44 4 60 2 625
runbg mrl5k_d3qn_M4_s0.json $COMMON OFF_ALGO=d3qn PPO_SEED=0 -- offpol_hold.py sim_inputs.json mrl5k_d3qn_M4_s0.json 0.44 4 60 2 625
runbg mrl5k_d3qn_M4_s1.json $COMMON MKL_NUM_THREADS=2 OFF_ALGO=d3qn OMP_NUM_THREADS=2 PPO_SEED=1 -- offpol_hold.py sim_inputs.json mrl5k_d3qn_M4_s1.json 0.44 4 60 2 625
runbg mrl5k_d3qn_M4_s2.json $COMMON MKL_NUM_THREADS=2 OFF_ALGO=d3qn OMP_NUM_THREADS=2 PPO_SEED=2 -- offpol_hold.py sim_inputs.json mrl5k_d3qn_M4_s2.json 0.44 4 60 2 625
runbg mrl5k_d3qn_M4_s3.json $COMMON MKL_NUM_THREADS=2 OFF_ALGO=d3qn OMP_NUM_THREADS=2 PPO_SEED=3 -- offpol_hold.py sim_inputs.json mrl5k_d3qn_M4_s3.json 0.44 4 60 2 625
runbg mrl5k_d3qn_M4_s4.json $COMMON MKL_NUM_THREADS=2 OFF_ALGO=d3qn OMP_NUM_THREADS=2 PPO_SEED=4 -- offpol_hold.py sim_inputs.json mrl5k_d3qn_M4_s4.json 0.44 4 60 2 625
runbg mrl5k_td3_M4_s0.json $COMMON OFF_ALGO=td3 PPO_SEED=0 -- offpol_hold.py sim_inputs.json mrl5k_td3_M4_s0.json 0.44 4 60 2 625
runbg mrl5k_td3_M4_s1.json $COMMON MKL_NUM_THREADS=2 OFF_ALGO=td3 OMP_NUM_THREADS=2 PPO_SEED=1 -- offpol_hold.py sim_inputs.json mrl5k_td3_M4_s1.json 0.44 4 60 2 625
runbg mrl5k_td3_M4_s2.json $COMMON MKL_NUM_THREADS=2 OFF_ALGO=td3 OMP_NUM_THREADS=2 PPO_SEED=2 -- offpol_hold.py sim_inputs.json mrl5k_td3_M4_s2.json 0.44 4 60 2 625
runbg mrl5k_td3_M4_s3.json $COMMON MKL_NUM_THREADS=2 OFF_ALGO=td3 OMP_NUM_THREADS=2 PPO_SEED=3 -- offpol_hold.py sim_inputs.json mrl5k_td3_M4_s3.json 0.44 4 60 2 625
runbg mrl5k_td3_M4_s4.json $COMMON MKL_NUM_THREADS=2 OFF_ALGO=td3 OMP_NUM_THREADS=2 PPO_SEED=4 -- offpol_hold.py sim_inputs.json mrl5k_td3_M4_s4.json 0.44 4 60 2 625
waitall
report
