#!/bin/bash
# retrained variants of the learners: structure ablation, one / two token levels, other recall requirements, earlier protocols that a figure still reads
# GENERATED by tools/build.py from the as-run chain scripts (as_run/) - edit the generator, not this file.
# usage: bash exp/12_train_variants.sh        (settings: env.sh; output directory: $OUT; SMOKE=1 for a quick execution test)
source "$(dirname "$0")/../lib.sh"

COMMON="BUB_ALTS=39,69.5,100 BUB_IOT_DB=20.1 BUB_NTOK_CV=0 BUB_PORTS=4 BUB_QBAR=0.44 BUB_QMARGIN=0.008 BUB_V=0.3 BUB_ZMODE=uav EVAL_LAMS=55,60,65 PPO_LAMS=55,60,65 PPO_LAMS_TEST=60,65"

runbg sppoAb_pfix_s0.json $COMMON BUB_BETA=300 MKL_NUM_THREADS=2 OMP_NUM_THREADS=2 PPO_SEED=30 SPPO_FREEZE=p SPPO_LRS=1.5e-1 SPPO_MODE=struct -- sppo_hold.py sim_inputs.json sppoAb_pfix_s0.json 0.44 4 60 3 500
runbg sppoAb_pfix_s1.json $COMMON BUB_BETA=300 MKL_NUM_THREADS=2 OMP_NUM_THREADS=2 PPO_SEED=31 SPPO_FREEZE=p SPPO_LRS=1.5e-1 SPPO_MODE=struct -- sppo_hold.py sim_inputs.json sppoAb_pfix_s1.json 0.44 4 60 3 500
runbg sppoAb_pfix_s2.json $COMMON BUB_BETA=300 MKL_NUM_THREADS=2 OMP_NUM_THREADS=2 PPO_SEED=32 SPPO_FREEZE=p SPPO_LRS=1.5e-1 SPPO_MODE=struct -- sppo_hold.py sim_inputs.json sppoAb_pfix_s2.json 0.44 4 60 3 500
runbg sppoAb_vfix_s0.json $COMMON BUB_BETA=300 MKL_NUM_THREADS=2 OMP_NUM_THREADS=2 PPO_SEED=30 SPPO_FREEZE=V SPPO_LRS=1.5e-1 SPPO_MODE=struct -- sppo_hold.py sim_inputs.json sppoAb_vfix_s0.json 0.44 4 60 3 500
runbg sppoAb_vfix_s1.json $COMMON BUB_BETA=300 MKL_NUM_THREADS=2 OMP_NUM_THREADS=2 PPO_SEED=31 SPPO_FREEZE=V SPPO_LRS=1.5e-1 SPPO_MODE=struct -- sppo_hold.py sim_inputs.json sppoAb_vfix_s1.json 0.44 4 60 3 500
runbg sppoAb_vfix_s2.json $COMMON BUB_BETA=300 MKL_NUM_THREADS=2 OMP_NUM_THREADS=2 PPO_SEED=32 SPPO_FREEZE=V SPPO_LRS=1.5e-1 SPPO_MODE=struct -- sppo_hold.py sim_inputs.json sppoAb_vfix_s2.json 0.44 4 60 3 500
runbg sppoF_p1_s0.json $COMMON BUB_BETA=100 PPO_SEED=30 SPPO_LRS=5e-2 SPPO_MODE=struct -- sppo_hold.py sim_inputs.json sppoF_p1_s0.json 0.44 4 60 4 500
runbg sppoF_p1_s1.json $COMMON BUB_BETA=100 PPO_SEED=31 SPPO_LRS=5e-2 SPPO_MODE=struct -- sppo_hold.py sim_inputs.json sppoF_p1_s1.json 0.44 4 60 4 500
runbg sppoF_p1_s2.json $COMMON BUB_BETA=100 PPO_SEED=32 SPPO_LRS=5e-2 SPPO_MODE=struct -- sppo_hold.py sim_inputs.json sppoF_p1_s2.json 0.44 4 60 4 500
runbg sppoF_p1_s3.json $COMMON BUB_BETA=100 PPO_SEED=33 SPPO_LRS=5e-2 SPPO_MODE=struct -- sppo_hold.py sim_inputs.json sppoF_p1_s3.json 0.44 4 60 4 500
runbg sppoF_p1_s4.json $COMMON BUB_BETA=100 PPO_SEED=34 SPPO_LRS=5e-2 SPPO_MODE=struct -- sppo_hold.py sim_inputs.json sppoF_p1_s4.json 0.44 4 60 4 500
runbg sppoL1_s0.json $COMMON BUB_BETA=300 BUB_LEVELS=0.48 MKL_NUM_THREADS=2 OMP_NUM_THREADS=2 PPO_SEED=30 SPPO_LRS=1.5e-1 SPPO_MODE=struct -- sppo_hold.py sim_inputs.json sppoL1_s0.json 0.44 4 60 3 500
runbg sppoL1_s1.json $COMMON BUB_BETA=300 BUB_LEVELS=0.48 MKL_NUM_THREADS=2 OMP_NUM_THREADS=2 PPO_SEED=31 SPPO_LRS=1.5e-1 SPPO_MODE=struct -- sppo_hold.py sim_inputs.json sppoL1_s1.json 0.44 4 60 3 500
runbg sppoL1_s2.json $COMMON BUB_BETA=300 BUB_LEVELS=0.48 MKL_NUM_THREADS=2 OMP_NUM_THREADS=2 PPO_SEED=32 SPPO_LRS=1.5e-1 SPPO_MODE=struct -- sppo_hold.py sim_inputs.json sppoL1_s2.json 0.44 4 60 3 500
runbg sppoL2_s0.json $COMMON BUB_BETA=300 BUB_LEVELS=0.44,0.48 MKL_NUM_THREADS=2 OMP_NUM_THREADS=2 PPO_SEED=30 SPPO_LRS=1.5e-1 SPPO_MODE=struct -- sppo_hold.py sim_inputs.json sppoL2_s0.json 0.44 4 60 3 500
runbg sppoL2_s1.json $COMMON BUB_BETA=300 BUB_LEVELS=0.44,0.48 MKL_NUM_THREADS=2 OMP_NUM_THREADS=2 PPO_SEED=31 SPPO_LRS=1.5e-1 SPPO_MODE=struct -- sppo_hold.py sim_inputs.json sppoL2_s1.json 0.44 4 60 3 500
runbg sppoL2_s2.json $COMMON BUB_BETA=300 BUB_LEVELS=0.44,0.48 MKL_NUM_THREADS=2 OMP_NUM_THREADS=2 PPO_SEED=32 SPPO_LRS=1.5e-1 SPPO_MODE=struct -- sppo_hold.py sim_inputs.json sppoL2_s2.json 0.44 4 60 3 500
waitall
runbg sppoF_p2_s0.json $COMMON BUB_BETA=100 PPO_SEED=40 SPPO_INIT=sppoF_p1_s0_final.pt SPPO_LRS=1e-2 SPPO_MODE=full -- sppo_hold.py sim_inputs.json sppoF_p2_s0.json 0.44 4 60 4 125
runbg sppoF_p2_s1.json $COMMON BUB_BETA=100 PPO_SEED=41 SPPO_INIT=sppoF_p1_s1_final.pt SPPO_LRS=1e-2 SPPO_MODE=full -- sppo_hold.py sim_inputs.json sppoF_p2_s1.json 0.44 4 60 4 125
runbg sppoF_p2_s2.json $COMMON BUB_BETA=100 PPO_SEED=42 SPPO_INIT=sppoF_p1_s2_final.pt SPPO_LRS=1e-2 SPPO_MODE=full -- sppo_hold.py sim_inputs.json sppoF_p2_s2.json 0.44 4 60 4 125
runbg sppoF_p2_s3.json $COMMON BUB_BETA=100 PPO_SEED=43 SPPO_INIT=sppoF_p1_s3_final.pt SPPO_LRS=1e-2 SPPO_MODE=full -- sppo_hold.py sim_inputs.json sppoF_p2_s3.json 0.44 4 60 4 125
runbg sppoF_p2_s4.json $COMMON BUB_BETA=100 PPO_SEED=44 SPPO_INIT=sppoF_p1_s4_final.pt SPPO_LRS=1e-2 SPPO_MODE=full -- sppo_hold.py sim_inputs.json sppoF_p2_s4.json 0.44 4 60 4 125
waitall
report
