#!/bin/bash
# the rules on the validation traffic (reference lines of the learning curves)
# GENERATED by tools/build.py from the as-run chain scripts (as_run/) - edit the generator, not this file.
# usage: bash exp/20_validation_refs.sh        (settings: env.sh; output directory: $OUT; SMOKE=1 for a quick execution test)
source "$(dirname "$0")/../lib.sh"

COMMON="BUB_ALTS=39,69.5,100 BUB_IOT_DB=20.1 BUB_NTOK_CV=0 BUB_PORTS=4 BUB_QBAR=0.44 BUB_QMARGIN=0.008 BUB_ZMODE=uav"

run   val_refs.json $COMMON  -- val_refs.py sim_inputs.json val_refs.json 0.44 4 $PROCS
run   val_refs_exh.json $COMMON EVAL_LAMS=55,60,65 MKL_NUM_THREADS=2 OMP_NUM_THREADS=2 PPO_LAMS=55,60,65 PPO_LAMS_TEST=60,65 VAL_POLS=lyapp2.5v0.1,lyapp3v0.1,lyapp4v0.1,lyapp3v0.2 -- val_refs.py sim_inputs.json val_refs_exh.json 0.44 4 $PROCS
report
