#!/bin/bash
# grid search over the two structure parameters (p, V) at M = 4, 60 flights/h
# GENERATED by tools/build.py from the as-run chain scripts (as_run/) - edit the generator, not this file.
# usage: bash exp/21_grid_search.sh        (settings: env.sh; output directory: $OUT; SMOKE=1 for a quick execution test)
source "$(dirname "$0")/../lib.sh"

COMMON="BUB_ALTS=39,69.5,100 BUB_IOT_DB=20.1 BUB_LAMS=60 BUB_MS=4 BUB_NTOK_CV=0 BUB_PORTS=4 BUB_QBAR=0.44 BUB_QMARGIN=0.008 BUB_ZMODE=uav STRAT_BUFS=0"

run   landscape_pv.json $COMMON BUB_POLS=lyapp1v0.01,lyapp1v0.02,lyapp1v0.03,lyapp1v0.05,lyapp1v0.1,lyapp1v0.2,lyapp1v0.3,lyapp1v0.5,lyapp1.5v0.01,lyapp1.5v0.02,lyapp1.5v0.03,lyapp1.5v0.05,lyapp1.5v0.1,lyapp1.5v0.2,lyapp1.5v0.3,lyapp1.5v0.5,lyapp2v0.01,lyapp2v0.02,lyapp2v0.03,lyapp2v0.05,lyapp2v0.1,lyapp2v0.2,lyapp2v0.3,lyapp2v0.5,lyapp2.5v0.01,lyapp2.5v0.02,lyapp2.5v0.03,lyapp2.5v0.05,lyapp2.5v0.1,lyapp2.5v0.2,lyapp2.5v0.3,lyapp2.5v0.5,lyapp3v0.01,lyapp3v0.02,lyapp3v0.03,lyapp3v0.05,lyapp3v0.1,lyapp3v0.2,lyapp3v0.3,lyapp3v0.5,lyapp3.5v0.01,lyapp3.5v0.02,lyapp3.5v0.03,lyapp3.5v0.05,lyapp3.5v0.1,lyapp3.5v0.2,lyapp3.5v0.3,lyapp3.5v0.5,lyapp4v0.01,lyapp4v0.02,lyapp4v0.03,lyapp4v0.05,lyapp4v0.1,lyapp4v0.2,lyapp4v0.3,lyapp4v0.5 CAP_SEEDS=12 -- cap_strat.py sim_inputs.json landscape_pv.json 0.44 cap $PROCS
run   landscape_pv_M4_48.json $COMMON BUB_POLS=lyapp2.5v0.05,lyapp2.5v0.075,lyapp2.5v0.1,lyapp2.5v0.15,lyapp3v0.05,lyapp3v0.075,lyapp3v0.1,lyapp3v0.15,lyapp3.5v0.05,lyapp3.5v0.075,lyapp3.5v0.1,lyapp3.5v0.15 CAP_SEEDS=48 -- cap_strat.py sim_inputs.json landscape_pv_M4_48.json 0.44 cap $PROCS
report
