#!/bin/bash
# ablations: structure parameters, number of token levels, constraint on the network average
# GENERATED by tools/build.py from the as-run chain scripts (as_run/) - edit the generator, not this file.
# usage: bash exp/32_ablation_levels.sh        (settings: env.sh; output directory: $OUT; SMOKE=1 for a quick execution test)
source "$(dirname "$0")/../lib.sh"

COMMON="BUB_ALTS=39,69.5,100 BUB_IOT_DB=20.1 BUB_NTOK_CV=0 BUB_PORTS=4 BUB_QBAR=0.44 CAP_SEEDS=48 MKL_NUM_THREADS=2 OMP_NUM_THREADS=2 STRAT_BUFS=0,30"

run   ablate48_M4.json $COMMON BUB_LAMS=55,60,65 BUB_MS=4 BUB_POLS='' BUB_QMARGIN=0.008 BUB_ZMODE=uav CAP_LEARNED=pfix0=sppoAb_pfix_s0_final.pt,vfix0=sppoAb_vfix_s0_final.pt,pfix1=sppoAb_pfix_s1_final.pt,vfix1=sppoAb_vfix_s1_final.pt,pfix2=sppoAb_pfix_s2_final.pt,vfix2=sppoAb_vfix_s2_final.pt CAP_RAW=1 CAP_SEED0=501 -- cap_strat.py sim_inputs.json ablate48_M4.json 0.44 cap $PROCS
run   final48_M3_lev1.json $COMMON BUB_LAMS=30,35,40 BUB_LEVELS=0.48 BUB_MS=3 BUB_POLS=lyap0.3,lyapp3v0.1,lyapp3v0.05 BUB_QMARGIN=0.008 BUB_ZMODE=uav CAP_LEARNED=l0=sppoL1_s0_final.pt,l1=sppoL1_s1_final.pt,l2=sppoL1_s2_final.pt CAP_RAW=1 CAP_SEED0=501 -- cap_strat.py sim_inputs.json final48_M3_lev1.json 0.44 cap $PROCS
run   final48_M3_lev2.json $COMMON BUB_LAMS=30,35,40 BUB_LEVELS=0.44,0.48 BUB_MS=3 BUB_POLS=lyap0.3,lyapp3v0.1,lyapp3v0.05 BUB_QMARGIN=0.008 BUB_ZMODE=uav CAP_LEARNED=t0=sppoL2_s0_final.pt,t1=sppoL2_s1_final.pt,t2=sppoL2_s2_final.pt,tb0=sppoL2_s0_best.pt,tb1=sppoL2_s1_best.pt,tb2=sppoL2_s2_best.pt CAP_SEED0=501 -- cap_strat.py sim_inputs.json final48_M3_lev2.json 0.44 cap $PROCS
run   final48_M4_lev1.json $COMMON BUB_LAMS=55,60,65 BUB_LEVELS=0.48 BUB_MS=4 BUB_POLS=lyap0.3,lyapp3v0.1,lyapp3v0.05 BUB_QMARGIN=0.008 BUB_ZMODE=uav CAP_LEARNED=l0=sppoL1_s0_final.pt,l1=sppoL1_s1_final.pt,l2=sppoL1_s2_final.pt CAP_RAW=1 CAP_SEED0=501 -- cap_strat.py sim_inputs.json final48_M4_lev1.json 0.44 cap $PROCS
run   final48_M4_lev1best.json $COMMON BUB_LAMS=55,60,65 BUB_LEVELS=0.48 BUB_MS=4 BUB_POLS='' BUB_QMARGIN=0.008 BUB_ZMODE=uav CAP_LEARNED=b0=sppoL1_s0_best.pt,b1=sppoL1_s1_best.pt,b2=sppoL1_s2_best.pt CAP_SEED0=501 -- cap_strat.py sim_inputs.json final48_M4_lev1best.json 0.44 cap $PROCS
run   final48_M4_lev2.json $COMMON BUB_LAMS=55,60,65 BUB_LEVELS=0.44,0.48 BUB_MS=4 BUB_POLS=lyap0.3,lyapp3v0.1,lyapp3v0.05 BUB_QMARGIN=0.008 BUB_ZMODE=uav CAP_LEARNED=t0=sppoL2_s0_final.pt,t1=sppoL2_s1_final.pt,t2=sppoL2_s2_final.pt,tb0=sppoL2_s0_best.pt,tb1=sppoL2_s1_best.pt,tb2=sppoL2_s2_best.pt CAP_SEED0=501 -- cap_strat.py sim_inputs.json final48_M4_lev2.json 0.44 cap $PROCS
run   final48_M4_lev4best.json $COMMON BUB_LAMS=55,60,65 BUB_MS=4 BUB_POLS='' BUB_QMARGIN=0.008 BUB_ZMODE=uav CAP_LEARNED=fb0=sppoX_fast5_s0_best.pt,fb1=sppoX_fast5_s1_best.pt,fb2=sppoX_fast5_s2_best.pt,fb3=sppoX_fast5_s3_best.pt,fb4=sppoX_fast5_s4_best.pt CAP_SEED0=501 -- cap_strat.py sim_inputs.json final48_M4_lev4best.json 0.44 cap $PROCS
run   final48_M5_lev1.json $COMMON BUB_LAMS=55,60,65 BUB_LEVELS=0.48 BUB_MS=5 BUB_POLS=lyap0.3,lyapp3v0.1,lyapp3v0.05 BUB_QMARGIN=0.008 BUB_ZMODE=uav CAP_LEARNED=l0=sppoL1_s0_final.pt,l1=sppoL1_s1_final.pt,l2=sppoL1_s2_final.pt CAP_RAW=1 CAP_SEED0=501 -- cap_strat.py sim_inputs.json final48_M5_lev1.json 0.44 cap $PROCS
run   lev1_rules.json $COMMON BUB_LAMS=55,60 BUB_LEVELS=0.48 BUB_MS=4 BUB_POLS=lyap0.3,lyapp3v0.1,lyapp3v0.05 BUB_QMARGIN=0.008 BUB_ZMODE=uav -- cap_strat.py sim_inputs.json lev1_rules.json 0.44 cap $PROCS
run   lev2_rules.json $COMMON BUB_LAMS=55,60 BUB_LEVELS=0.44,0.48 BUB_MS=4 BUB_POLS=lyap0.3,lyapp3v0.1,lyapp3v0.05 BUB_QMARGIN=0.008 BUB_ZMODE=uav -- cap_strat.py sim_inputs.json lev2_rules.json 0.44 cap $PROCS
run   lev4_rules.json $COMMON BUB_LAMS=55,60 BUB_MS=4 BUB_POLS=lyap0.3,lyapp3v0.1,lyapp3v0.05 BUB_QMARGIN=0.008 BUB_ZMODE=uav -- cap_strat.py sim_inputs.json lev4_rules.json 0.44 cap $PROCS
run   net_rules.json $COMMON BUB_LAMS=55,60,65 BUB_MS=4 BUB_POLS=fixed2,lyap10,lyap30,lyapp3v10,lyapp3v30 BUB_QMARGIN=0.004 BUB_ZMODE=net -- cap_strat.py sim_inputs.json net_rules.json 0.44 cap $PROCS
report
