#!/bin/bash
# behaviour diagnostics (when are tokens sent) and computation time per decision
# GENERATED by tools/build.py from the as-run chain scripts (as_run/) - edit the generator, not this file.
# usage: bash exp/40_behaviour_timing.sh        (settings: env.sh; output directory: $OUT; SMOKE=1 for a quick execution test)
source "$(dirname "$0")/../lib.sh"

COMMON="BUB_ALTS=39,69.5,100 BUB_IOT_DB=20.1 BUB_NTOK_CV=0 BUB_PORTS=4 BUB_QBAR=0.44 BUB_QMARGIN=0.008 BUB_ZMODE=uav MKL_NUM_THREADS=2"

run   diag_dpp.json $COMMON DG_KIND=rule DG_POL=lyap0.3 DG_PROCS=$PROCS OMP_NUM_THREADS=2 -- diag_levels.py sim_inputs.json diag_dpp.json 0.44 4 60
run   diag_exh.json $COMMON DG_KIND=rule DG_POL=lyapp3v0.1 DG_PROCS=$PROCS OMP_NUM_THREADS=2 -- diag_levels.py sim_inputs.json diag_exh.json 0.44 4 60
run   diag_prop.json $COMMON DG_CKPT=sppoX_fast5_s0_final.pt DG_KIND=sppo DG_PROCS=$PROCS OMP_NUM_THREADS=2 -- diag_levels.py sim_inputs.json diag_prop.json 0.44 4 60
run   time_B.json $COMMON BUB_BETA=500 BUB_POLS='' BUB_PRIOR_P=1 BUB_V=0.03 CAP_KIND=hppo OMP_NUM_THREADS=1 PPO_BASE=urg PPO_PRIOR=0 PPO_REWARD=queue TD_CKPT=mrl5k_B_M4_s0_best.pt TD_KIND=hppo -- time_decide.py sim_inputs.json time_B.json 0.44 4 60
run   time_d3qn.json $COMMON BUB_BETA=500 BUB_POLS='' BUB_V=0.03 OMP_NUM_THREADS=1 TD_CKPT=mrl5k_d3qn_M4_s0_best.pt TD_KIND=d3qn -- time_decide.py sim_inputs.json time_d3qn.json 0.44 4 60
run   time_fixed2.json $COMMON OMP_NUM_THREADS=1 TD_KIND=rule TD_POL=fixed2 -- time_decide.py sim_inputs.json time_fixed2.json 0.44 4 60
run   time_lyap0.3.json $COMMON OMP_NUM_THREADS=1 TD_KIND=rule TD_POL=lyap0.3 -- time_decide.py sim_inputs.json time_lyap0.3.json 0.44 4 60
run   time_lyapp3v0.1.json $COMMON OMP_NUM_THREADS=1 TD_KIND=rule TD_POL=lyapp3v0.1 -- time_decide.py sim_inputs.json time_lyapp3v0.1.json 0.44 4 60
run   time_prop.json $COMMON OMP_NUM_THREADS=1 TD_CKPT=sppoX_fast5_s0_final.pt TD_KIND=sppo -- time_decide.py sim_inputs.json time_prop.json 0.44 4 60
run   time_td3.json $COMMON BUB_BETA=500 BUB_POLS='' BUB_V=0.03 OMP_NUM_THREADS=1 TD_CKPT=mrl5k_td3_M4_s0_best.pt TD_KIND=td3 -- time_decide.py sim_inputs.json time_td3.json 0.44 4 60
report
