#!/bin/bash
# Reproduction check at full fidelity (48 traffic seeds), a few minutes: at M = 4, 60 flights/h, no buffer - on the test traffic a rule of each
# family, a trained policy of the proposed learner and the H-PPO baseline; on the development traffic a rule and a policy of the earlier
# two-phase protocol - with the shipped checkpoints, compared with the stored values
# (ref/expected.json, taken from the result files the tables are built from). GENERATED by tools/build.py.
source "$(dirname "$0")/../lib.sh"

FORCE=1 run check_M4_main.json BUB_ALTS=39,69.5,100 BUB_IOT_DB=20.1 BUB_LAMS=60 BUB_MS=4 BUB_NTOK_CV=0 BUB_POLS=lyap0.3,lyapp3v0.1 BUB_PORTS=4 BUB_QBAR=0.44 BUB_QMARGIN=0.008 BUB_ZMODE=uav CAP_LEARNED=f0=sppoX_fast5_s0_final.pt CAP_SEED0=501 CAP_SEEDS=48 MKL_NUM_THREADS=2 OMP_NUM_THREADS=2 STRAT_BUFS=0 -- cap_strat.py sim_inputs.json check_M4_main.json 0.44 cap $PROCS
FORCE=1 run check_M4_B.json BUB_ALTS=39,69.5,100 BUB_BETA=500 BUB_IOT_DB=20.1 BUB_LAMS=60 BUB_MS=4 BUB_NTOK_CV=0 BUB_POLS='' BUB_PORTS=4 BUB_PRIOR_P=1 BUB_QBAR=0.44 BUB_QMARGIN=0.008 BUB_V=0.03 BUB_ZMODE=uav CAP_KIND=hppo CAP_LEARNED=ppo=mrl5k_B_M4_s0_best.pt CAP_SEED0=501 CAP_SEEDS=48 MKL_NUM_THREADS=2 OMP_NUM_THREADS=2 PPO_BASE=urg PPO_PRIOR=0 PPO_REWARD=queue STRAT_BUFS=0 -- cap_strat.py sim_inputs.json check_M4_B.json 0.44 cap $PROCS
FORCE=1 run check_M4_dev.json BUB_ALTS=39,69.5,100 BUB_IOT_DB=20.1 BUB_LAMS=60 BUB_MS=4 BUB_NTOK_CV=0 BUB_POLS=lyapp3v0.03 BUB_PORTS=4 BUB_QBAR=0.44 BUB_QMARGIN=0.008 BUB_ZMODE=uav CAP_LEARNED=s1=sppoF_p2_s1_final.pt CAP_SEEDS=48 MKL_NUM_THREADS=2 OMP_NUM_THREADS=2 STRAT_BUFS=0 -- cap_strat.py sim_inputs.json check_M4_dev.json 0.44 cap $PROCS
$PY "$REPRO/tools/compare.py" "$OUT" "$REPRO/ref/expected.json"
report
